### ISSUE TITLE
Adjust bank and log permissions after settings are configurable from file

### ISSUE THREAD

**Issue by Comeani** [pitt-crc/bank#323]
``` 
Submitted on Wednesday, August 30, 2023 - 11:38

Submitted by user: DKOES

Submitted values are:

Pitt email: [DKOES@pitt.edu](mailto:DKOES@pitt.edu)

What is the cluster's name you are working on? GPU

What is the full path to your submission script? NA

Subject: crc-usage not working

Describe your Request:

```bash

[dkoes@login1 ~]$ crc-usage

Traceback (most recent call last):

File "/ihome/crc/pipx/bin/crc-usage", line 5, in

from apps.crc_usage import CrcUsage

File "/ihome/crc/pipx/opt/venvs/crc-wrappers/lib64/python3.9/site-packages/apps/crc_usage.py", line 11, in

from bank.account_logic import AccountServices

File "/ihome/crc/pipx/opt/venvs/crc-wrappers/lib64/python3.9/site-packages/bank/__init__.py", line 17, in

logging.basicConfig(

File "/usr/lib64/python3.9/logging/__init__.py", line 2003, in basicConfig

h = FileHandler(filename, mode,

File "/usr/lib64/python3.9/logging/__init__.py", line 1146, in __init__

StreamHandler.__init__(self, self._open())

File "/usr/lib64/python3.9/logging/__init__.py", line 1175, in _open

return open(self.baseFilename, self.mode, encoding=self.encoding,

PermissionError: [Errno 13] Permission denied: '/ihome/crc/bank/crc_bank.log'
```
chmod o+w for now on the log (`/ihome/crc/bank/crc_bank.log`) to fix this.

**Comment by Comeani** [comment]
We are making only critical changes to keep the bank working until we start using keystone
